language: node_js
  - 16.8.0
sudo: required
services:
  - docker

before_install:
  - docker build -t alexc101/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alexc101/docker-react npm run test -- --coverage
