language: node_js
node_js:
  - node  
  - lts/* 

sudo: required
services:
  - docker

before_install:
  - docker build -t alexc101/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alexc101/docker-react npm run test -- --coverage

deploy:
  provider: elsaticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-west-2-791679193292"
  bucket_path: "Dockerreact"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY