language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t alexc101/docker-react -f Dockerfile.dev .

script:
  - docker run -e alexc101/docker-react CI=true alexc101/docker-react npm run test
